### PR TITLE
Danish translation

### PR DESCRIPTION
**Pull request by emmilinette**
With @Alkarex

### CODE REVIEW

**Comment by Deevad** [comment]
Thank you @emmilinette and @Alkarex  ! 

I saw in the log of the IRC chat @Alkarex connected for question about the cover of Pepper&Carrot ; sorry I was coloring episode 22 in full-screen during this time and I wasn't around and I'm not sure after reading the log he had answers to his questions. You can connect again this week; I'm releasing ep22 this afternoon.

This week, after release of ep22, I decided to complete this project : https://github.com/Deevad/peppercarrot_print_book01  ; and I plan to make it dynamic so it will be easy to change the lang with just a batch "replace" of strings ```en_``` to ```da_``` for example in all the XML files (Scribus ```*.sla``` files are structured this way, easy). I hope this open-source publishing project will help various smaller self-publishing project. 

Thank you for ep12 translation!

**Comment by Alkarex** [comment]
Ah, excellent, this is even more than what we were looking for :-)
We will of course do the Danish version. Let us know if it becomes possible to buy copies :-)

**Comment by Alkarex** [comment]
@Deevad Arg, some of the sound effect texts have not been rendered this time
https://www.peppercarrot.com/da/article331/episode-12-autumn-clearout

image

image

Although the *Klang* is in the SVG:
https://github.com/emmilinette/peppercarrot_ep12_translation/blob/b8441c9699cc81da39c196c235e27479132cb2bb/da/Pepper-and-Carrot_by-David-Revoy_E12P01.svg?short_path=296b61a#L458

Example for the *Kling*:

```xml
<flowRoot
       xml:space="preserve"
       id="flowRoot2987-7-9-9-7-0-3-4-1"
       style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;line-height:0.01%;font-family:Lavi;-inkscape-font-specification:Lavi;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:#000000;stroke-width:0.99236238;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;filter:url(#filter4375-4-1-1-1)"
       transform="matrix(1.1266937,-0.74193901,0.96098551,1.8412031,192.63293,2227.977)"><flowRegion
         id="flowRegion2989-4-5-8-7-41-7-62-2"
         style="stroke-width:5.40286207"><rect
           id="rect2991-45-1-3-3-8-0-4-6"
           width="319.66232"
           height="53.089447"
           x="120.55251"
           y="265.53046"
           style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-family:Lavi;-inkscape-font-specification:Lavi;fill:#000000;fill-opacity:1;stroke:#000000;stroke-width:0.99236238;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1" /></flowRegion><flowPara
         id="flowPara2995-4-1-5-0-7-2-6-4"
         style="font-weight:normal;font-size:48px;line-height:1.25;-inkscape-font-specification:Lavi;letter-spacing:7.06853437px;fill:#ffffff;fill-opacity:1;stroke:#ffffff;stroke-width:0.99236238;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1">Kling</flowPara></flowRoot>
```

As they do not appear in Inkscape, I just changed the text manually in the SVG files without altering the markup.

Any tip on how to fix?

**Comment by Deevad** [comment]
Hey, thank you for double checking the uploaded translation @Alkarex ; I see in the SVG header you are using Inkscape 0.92.1 , and here the renderfarm use it too. So, we should get a perfect compatibility and pure WYSIWG between your computer and mine. But I confirm the bug : my Inkscape can't display the sound effect. Even worst: my new version of Inkscape ( 0.92.1 from Inkscape stable PPA on Ubuntu 16.04 , updated last week to render properly ep22 translations sent with newer version )  doesn't display any of sound effect in page 1 over all the other translations , and same for sound effect of episode 11, and under I suppose... 

I think it's related to my old usage of "flowed text" the default text-box proposed by Inkscape ; not a standard with SVG ; but enforced in Inkscape. I saw it only on episode 13 , and then made all translation use non-flowed text after 13 and up because I was feeling this Inkscape-only SVG markup would be problematic sooner or later... And there it is ! After the crap of 0.92 Inkscape, even with the fix 0.92.1 can't read properly SVG markup of Inkscape 0.91 for flowed-text. I don't know what to do :/ 

One weird thing : it looks like your Inkscape 0.92.1 can display/edit them. Maybe it's a newer Inkscape version ; mine display in the header ```inkscape:version="0.92.1 unknown"``` while your ``` inkscape:version="0.92.1 r15371"```. If it's fixed in a newer version ; I probably can try to update my renderfarm to this version. Let me know how you get this version :-)


2017-05-30_screenshot_104758

**Comment by Alkarex** [comment]
Do you say you have updated the render farm recently?
It seemed to work for our previous pull request https://github.com/Deevad/peppercarrot_ep11_translation/pull/31
Yes, we did all episodes 1-12 by changing the sound effect texts manually in the SVG, as none appeared in Inkscape.
Let me know when you are able to render the French version correctly, and I can re-do the Danish version if needed.

**Comment by Alkarex** [comment]
P.S. The Inkscape we used is the one included in Ubuntu 17.04 on my daughter's laptop https://packages.ubuntu.com/zesty/inkscape
But it is not able to show any of those special texts

**Comment by Deevad** [comment]
Interesting. Yes, I updated the renderfarm **very** recently ; something like four or five days ago. So I rendered episode 11 [da] with 0.91 stock version from Ubuntu 16.04 (Linux Mint 18.1 with XFCE to be more precise, but 16.04 ecosystem) .  I updated to 0.92.1 with a PPA. Good to know the 0.92.1 you have on the laptop of your daughter with 17.04 also doesn't show the special effects. 

I think I'll need the help of a Inkscape developer to see if a big replacement of string on the SVG code over all the flowed-text box can solve this situation. Sometime, it's related to wrong size conversion or new default line-height ; just a minor value to tweak. It can worth a little investigation. I'll do it as soon as possible ; because I want to keep 0.92.1 in the renderfarm and I also wants to be able to render properly all episode from 01 to 12 ( all pages in all translations of this one are affected in case of re-rendering ).  I take it very seriously. I'll give you news as soon I have more informations. thanks again for spotting the issue.

**Comment by Alkarex** [comment]
Very good. In the meantime, could you so render episode 12 in Danish with the previous version?

**Comment by Deevad** [comment]
Unfortunately, I can't get two version of Inkscape side by side and programming a conditional switch to the renderfarm script today. Making this rigg can take time and needs experimentation. The renderfarm right now calls /usr/bin/inkscape to render the SVG and has no idea of the version in usage, nor know what episode number is rendered. Making the script aware of the episode, and installing a self contained Inkscape 0.91 in another path than /usr/bin/inkscape is a lot of work for a work around.

What I can do for the short-term solution is to remove the translated version temporary if you prefer. Let me know, and I'll clean the ```da_*``` files from the server.

**Comment by Alkarex** [comment]
OK, I thought you would have the possibility of making a manual rendering and uploading of the PNGs. If not possible, just leave it as it is, then.

**Comment by Deevad** [comment]
Hey, Thanks to **Mc** on IRC channel, I have feedback:

This is this bug: https://bugs.launchpad.net/inkscape/+bug/1513959 : The flowed-region boundary box is smaller than the content ( Inkscape 0.92.1 probably understand all the text to be slightly bigger than 0.91 and then not display them because the content is going outside the boundaries.). 

A quick extension of the box from 53 to 56 as in https://github.com/Deevad/peppercarrot_ep12_translation/commit/b4d2eea39a7778c080855ec043c8fdf3137b75d6 fixed it ( as seen online here: https://www.peppercarrot.com/da/article331/episode-12-autumn-clearout  ) .  More sound FX remains, I'll fix them later.

I think Inkscape 0.92.1 will force me to have to do this type of manual tweak over all the repo from ep01 to ep12. I'll try to see if a batch method can be done.

**Comment by Alkarex** [comment]
The rest of the episode should be fixed in https://github.com/Deevad/peppercarrot_ep12_translation/pull/19 with this trick.
It looks like a simple search & replace of `53.089447` by `56.089447` works.

**Comment by Alkarex** [comment]
@Deevad I can do the fix in Episodes 1-11 in Danish, but you could maybe consider doing all languages at once. Let me know.

**Comment by Deevad** [comment]
Super, it looks like you found the magic number; I also got this same exact numeric in episode 6, so I think it's a Inkscape thing. I'll see if I can batch 'sed' this , and find other "magic numbers" for older episode. That's a super hint to fix the repos. Thank you!

**Comment by Alkarex** [comment]
It looks like this precise number also is used in episodes 1-11.

**Comment by Deevad** [comment]
I confirm ; still in a long recursive ```grep``` , and I'm hitting a lot of results:

2017-05-31_screenshot_154826

**Pull request merged**
