### PR TITLE
Lojban: grammar fixes

### PR DESCRIPTION
**Pull request by mezohe**

### CODE REVIEW

**Comment by Deevad** [comment]
Hey @mezohe , thank you for all the pull-request and polishing pass over the Lojban lang. 
Do you know @lagleki ? He made the initial translation in Lojban. 
I'll merge all the pull-request on Monday if @lagleki is OK with it and update the comic. Feel free to add a 'corrected by <yourname>' in the README file for attribution :-)
Have a good sunday!

**Comment by lagleki** [comment]
i lo'u se mo'u le'u zo'u e'u pilno zo ca

**Comment by lagleki** [comment]
i lo gaspo zo'u ie

**Comment by mezohe** [comment]
@lagleki mo'u basygau
@Deevad We've just discussed the changes and made some corrections. The requests should be ready to merge now.

**Comment by lagleki** [comment]
Let's merge it.

**Comment by Deevad** [comment]
@lagleki : thanks for the review! 
@mezohe : thanks for the contribution. 
Ok, let's merge all and update all :-)

**Pull request merged**
